import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { Toaster } from "@/components/ui/sonner";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  isAuthPage?: boolean;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <div className="bg-black text-white mx-auto flex flex-col  max-w-7xl w-full min-h-screen  px-4 sm:px-6 md:px-8 lg:px-12">
          <Toaster />
          <Navbar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
