import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { Toaster } from "@/components/ui/sonner";
import { TRPCReactProvider } from "@/trpc/client";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { uploadRouter } from "./api/uploadthing/core";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  isAuthPage?: boolean;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <TRPCReactProvider>
          <div className="bg-black text-white mx-auto flex flex-col  max-w-7xl w-full min-h-screen  px-4 sm:px-6 md:px-8 lg:px-12">
            <NextSSRPlugin routerConfig={extractRouterConfig(uploadRouter)} />
            <Toaster />
            <Navbar />
            <main>{children}</main>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
